# Generated by Django 3.2.8 on 2021-11-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InbodyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndiaRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meachine_name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InbodyBook.indiaregions')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_mobile', models.BigIntegerField()),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=100)),
                ('addr2', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('demo_meachine', models.CharField(max_length=50)),
                ('inbodyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InbodyBook.inbodyuser')),
                ('meachine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InbodyBook.meachines')),
            ],
        ),
    ]
