# Generated by Django 3.2.8 on 2021-12-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InbodyBook', '0003_rename_status_meachines_booked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meachines',
            new_name='Machine',
        ),
    ]
